name: test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2

      - name: 'Install packages'
        run: pnpm install

      - name: 'Lint'
        run: pnpm run lint

      - name: 'TypeScript'
        run: pnpm run test:types

      - name: 'Build'
        run: pnpm run build

      - name: Cypress PNPM Patch
        run: cp pnpm-lock.yaml package-lock.json

      - uses: cypress-io/github-action@v4
        with:
          # env: PORT=4000
          build: pnpm run build
          start: pnpm run start
